### ISSUE TITLE
Publication on OPAM

### ISSUE THREAD

**Issue by pveber** [cyril-allignol/ocaml-shapefile#4]
Would it be ok to publish the library as an opam package? I can do it if you lack the time to proceed.

**Comment by cyril-allignol** [comment]
I already have an opam package on a private opam repository. It is out of date, but I could easily make the required changes and push it to the main opam repo. I'll take a look at it in the coming days.

**Comment by pveber** [comment]
sounds good, thanks!

**Comment by cyril-allignol** [comment]
The package has been integrated to the main opam repository.

**Comment by pveber** [comment]
Thanks!
